services:
  database:
    image: 'mysql:latest'
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_DATABASE: drury_mirror
    ports:
      - '3307:3306'

volumes:
  database:
